### ISSUE TITLE
When switching to the next page, Bookworm reports the content of the first line as blank

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#123]
## Describe the Problem
When switching to the next page, Bookworm does not correctly report the contents of the first line and instead reports "blank".

## To Reproduce

1. Download the Test pdf document and open it in Bookworm;
2. Press ctrl + G to go to page 9(or other page)
3. Press the up arrow twice quickly to go back to the last line on page 8, nvda report:"that your mind is not at ease when it is not mindful.";
4. Then press the down arrow once to let Bookworm switch to page 9;
5. NVDA reports the following:"blank, Page 9 of 105".

## Expected behavior
nvda should report the first line of page 9:"I want to be free and peaceful, bodily and mentally. So IÕm looking to see what makes a person not free and not peaceful. The"

## The File You've Opened
[test.zip](https://github.com/blindpandas/bookworm/files/8211753/test.zip)

## Desktop (please complete the following information):

 - OS: Windows 10 21H2 (x64) build 19044.1526
 - Bookworm 2022.1b1
 - Recent settings you may have changed in Bookworm  none

## Additional context
The above issue is based on NVDA2021.3.3

**Comment by mush42** [comment]
Hello @cary-rowen 

I confirm this issue. It is a side effect of how the continuous reading feature is implemented.

There is a background thread that tracks the position of the caret, and changes to the next page when the caret is at the end of the current page. The thread runs this check every second or so. While the background thread is switching pages, NVDA will speak the last line of the current page rather than the first line of the next page. This is a classic concurrency bug.

Unfortunately, I'll do nothing about this one. This is a low impact bug.

I exhausted all the possible options to come up with a stable implementation for the continuous reading feature, and I found none.

Best
Musharraf

**Comment by cary-rowen** [comment]
Hi @mush42 
Thanks for your patient reply.
Grateful

**Comment by mush42** [comment]
@cary-rowen 

No problem.

I am amazed at your effort, dedication, and patience to hunt for, and report bugs.

You and @DraganRatkovich are doing a great job, and I'm very grateful to you for that.

So please keep those issues coming!

Best
Musharraf

**Comment by cary-rowen** [comment]
Hi @mush42 
Hi, someone on this issue has suggested a possibly not-so-beautiful solution to insert a real blank line for every page wrap so they don't have to repeatedly hit the up and down arrows to confirm what the first line is.
I'd rather hear what you think about it.
Grateful

**Comment by mush42** [comment]
@cary-rowen 
That's a clever idea.
Let's try that and see how it effects the reading experience.

**Comment by mush42** [comment]
@cary-rowen 

The "empty line" suggestion is  a great improvement to the user experience. I've added it, and it will be a part of the next release.

best
Musharraf

**Comment by cary-rowen** [comment]
Hi @mush42 
I have tested this and it works great , thanks for your effort.
Grateful
Cary
到目前为止
