### ISSUE TITLE
Bookworm and ePub files

### ISSUE THREAD

**Issue by mush42** [blindpandas/bookworm#85]
### Discussed in https://github.com/blindpandas/bookworm/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **Cambridgeport90** December 23, 2021</sup>
I have noticed that when different Epub files are opened with Bookworm, depending on their formatting, it seems that the entire book is somehow missing... it will skip over the entire content of the book unless each chapter or section is clearly marked out in the table of contents. Otherwise, nothing happens. I wanted to post a discussion in the event that this isn't a bug but just a weird quirk. running Windows 10 and the latest version of Bookworm beta; beta 0.4.</div>

**Comment by Cambridgeport90** [comment]
I will be keeping an eye on this.

From: Musharraf ***@***.***>
Sent: Thursday, December 23, 2021 11:32 AM
To: blindpandas/bookworm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [blindpandas/bookworm] Bookworm and ePub files (Issue #85)

Discussed in #84<https://github.com/blindpandas/bookworm/discussions/84>

Originally posted by Cambridgeport90 December 23, 2021
I have noticed that when different Epub files are opened with Bookworm, depending on their formatting, it seems that the entire book is somehow missing... it will skip over the entire content of the book unless each chapter or section is clearly marked out in the table of contents. Otherwise, nothing happens. I wanted to post a discussion in the event that this isn't a bug but just a weird quirk. running Windows 10 and the latest version of Bookworm beta; beta 0.4.

**Comment by TheQuinbox** [comment]
Yup, I can confirm this. I've found that it primarily happens with Bookshare books. Dreadfully, this is the one task I have to keep QRead around for.

**Comment by mush42** [comment]
@TheQuinbox 

Have you tested this with the latest alpha v2022.a3. I think this issue has been fixed there.
